GET http://localhost:3000/users

###

GET    http://localhost:3000/level
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtzdXNoIiwiaWF0IjoxNzAyMjg5NTY1fQ.Ry1XPETUsgaTI7IWO3zkK6-NgUJgqo6tIKZGKrPiWN4
Content-Type: application/json

{
    "maxTasksInRoom": 3
}

###

POST   http://localhost:3000/users/create
Content-Type: application/json

{
    "username": "kkk",
    "password": "111111",
    "name":"asdddsd",
    "surname": "Karap"
}

###

GET    http://localhost:3000/users/leaders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtzdXNoIiwiaWF0IjoxNzAyMjg5NTY1fQ.Ry1XPETUsgaTI7IWO3zkK6-NgUJgqo6tIKZGKrPiWN4
Content-Type: application/json

{

}

###

POST    http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "ma123",
    "password": "111"
}

###
POST    http://localhost:3000/users/update/personal
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtzdXNoIiwiaWF0IjoxNzAyMjE2MzU2fQ.kyL9xq_HjPg46DTAXiRZnj4iMDJSX31NwLjx_UsBQts
Content-Type: application/json

{
     "name":"gay",
    "surname": "gayskiy"
}

###
POST    http://localhost:3000/users/update/password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtzdXNoIiwiaWF0IjoxNzAyMjE3NTU5fQ.fVSi_4qwjZ4ZBwTvLB70EktRCvAZdJOueNUa9XSg9_0
Content-Type: application/json

{
    "newPassword": "222"
}

###
DELETE http://localhost:3000/users/deleteuser
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImtzdXNoIiwiaWF0IjoxNzAyMjE3NTU5fQ.fVSi_4qwjZ4ZBwTvLB70EktRCvAZdJOueNUa9XSg9_0
Content-Type: application/json

{
    
}

###
DELETE http://localhost:3000/users
Content-Type: application/json

{
    
}

###
POST    http://localhost:3000/users/update/progress
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1hMTIzIiwiaWF0IjoxNzAzMTA5MDQ1fQ.JA7G4HYmsMV7p8mpdyubO2z8ZjS9r488L2LHktE00YI
Content-Type: application/json

{
    "points":"2",
    "crntLvl": "0",
    "timeStamp": "2023-12-20T14:24:06"
}


